language: php
php:
  - '7.1'

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - ./vendor/bin/phpmd src xml ruleset.xml --reportfile phpmd_report.xml
  - phpunit --configuration tests/phpunit.xml --coverage-text