<?php


namespace Tests\Tools;


class ES_TestHelper extends TestHelper
{
    protected static $EsPath = "http://elastic:changeme@0.0.0.0:9200";
    private static $dockerPort;
    private static $dockerName;

    public static function setUpBeforeClass()
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
//        $ES_Port = mt_rand(15000, 64000);
//        $dockerName = uniqid();
//        self::$dockerPort = $ES_Port;
//        self::$dockerName = $dockerName;
//        $ES_Host = '0.0.0.0';
//        self::$EsPath = 'http://elastic:changeme@0.0.0.0:'.$ES_Port;
//        shell_exec('docker run -p '.$ES_Port.':9200 -e "http.host='.$ES_Host.'" -d --name='.$dockerName.' -e "transport.host=127.0.0.1" docker.elastic.co/elasticsearch/elasticsearch:5.4.0');
//        echo "======================================="."\n";
//        echo "*     Waiting for docker ES boot.     *"."\n";
//        echo "======================================="."\n";
//        sleep(15);
    }

    public static function tearDownAfterClass()
    {
        parent::tearDownAfterClass(); // TODO: Change the autogenerated stub
//        shell_exec("docker rm -f ".self::$dockerName);

    }


}